# Generated by Django 2.2 on 2020-03-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerdiaryitem',
            name='flavour',
            field=models.IntegerField(choices=[(0, 'Alcohol'), (1, 'Hoppy'), (3, 'Floral'), (4, 'Spicy'), (5, 'Malty'), (6, 'Burnt'), (7, 'Sweet'), (8, 'Sour'), (9, 'Bitter'), (10, 'Dry'), (11, 'Linger')], default=0),
        ),
        migrations.AddField(
            model_name='beerdiaryitem',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=0),
        ),
    ]
